import type { Bonus } from "@/types/content";

/**
 * Seed bonus records tied to operators (FR-013).
 *
 * Authenticity (Constitution Principle V): titles are neutral, honest
 * placeholders that direct users to verify the current offer on the operator's
 * site. No fabricated amounts, no fabricated urgency/countdowns.
 *
 * Optional directory fields power /bonos V2. offerLabel / minDeposit / wagering
 * only include values already published in editorial copy or operator terms text.
 */
export const bonuses: Bonus[] = [
  {
    id: "stake-welcome",
    casinoId: "stake",
    title: "Consulta la promoción de bienvenida vigente",
    type: "welcome",
    terms: "Aplican términos y condiciones del operador. Verifica la oferta actual en el sitio oficial.",
    active: true,
    product: "casino",
    market: "global",
    status: "pending-verification",
  },
  {
    id: "caliente-welcome",
    casinoId: "caliente",
    title: "Consulta el bono de bienvenida vigente",
    type: "welcome",
    terms: "Aplican términos y condiciones del operador. Verifica la oferta actual en el sitio oficial.",
    active: true,
    product: "mixed",
    market: "mx",
    status: "pending-verification",
  },
  {
    id: "codere-welcome",
    casinoId: "codere",
    title: "Consulta la promoción de apuestas vigente",
    type: "welcome",
    terms: "Aplican términos y condiciones del operador. Verifica la oferta actual en el sitio oficial.",
    active: true,
    product: "sportsbook",
    market: "mx",
    status: "pending-verification",
  },
  {
    id: "betsson-welcome",
    casinoId: "betsson",
    title: "Consulta la promoción de bienvenida vigente",
    type: "welcome",
    terms:
      "Promoción publicada por Betsson MX. Bonos, giros, métodos de pago, verificación y retiros dependen de los términos oficiales del operador y de tu jurisdicción.",
    active: true,
    product: "casino",
    market: "mx",
    status: "active-variable",
    offerLabel: "Hasta $15,000 MXN + 200 giros gratis",
    minDeposit: "Desde $200 MXN (SPEI desde $100 según términos)",
    productLabel: "Casino fiat MX",
    directoryGroup: "casino-mx",
    featuredPosition: 1,
  },
  {
    id: "500-casino-welcome",
    casinoId: "500-casino",
    title: "Promociones visibles según términos oficiales",
    type: "welcome",
    terms:
      "Verifica promociones, requisitos de apuesta, disponibilidad, pagos y retiros directamente en 500 Casino.",
    active: true,
    product: "casino",
    market: "global",
    status: "active-variable",
  },
  {
    id: "rainbet-promotions",
    casinoId: "rainbet",
    title: "Promociones, rewards y free spins según términos oficiales",
    type: "welcome",
    terms:
      "La página pública de promociones muestra Wager Lock Promotion, No Wager Lock Promotion, bonos de primer depósito y free spins. Depósito mínimo $30 y máximo $700 según información publicada. Verifica requisitos de apuesta, juegos elegibles, elegibilidad por país, free spins de Pragmatic Play y condiciones antes de depositar.",
    active: true,
    product: "rewards",
    market: "global",
    status: "active-variable",
    minDeposit: "Desde $30 (máx. $700 según info publicada)",
  },
  {
    id: "betfury-welcome",
    casinoId: "betfury",
    title: "Hasta 590% + Free Spins según términos oficiales",
    type: "welcome",
    terms:
      "Promoción visible en Bonus Cabinet. Bonos, free spins, cashback, retiros y verificación dependen de los términos oficiales de BetFury.",
    active: true,
    product: "rewards",
    market: "global",
    status: "active-variable",
    offerLabel: "Hasta 590% + Free Spins según términos oficiales",
    productLabel: "Crypto · rewards",
    directoryGroup: "crypto-rewards",
    featuredPosition: 2,
  },
  {
    id: "1xbet-casino-welcome-package",
    casinoId: "1xbet",
    title: "Paquete de bienvenida: hasta 40,000 MXN + 150 giros gratis",
    type: "welcome",
    terms:
      "Oferta mostrada por 1xBet para nuevos usuarios. El paquete puede depender de depósitos elegibles, requisitos de apuesta, juegos participantes, límites, vencimiento, verificación y jurisdicción. Confirma la promoción vigente antes de depositar.",
    active: true,
    product: "casino",
    market: "mx",
    status: "active-variable",
    offerLabel: "Hasta 40,000 MXN + 150 giros gratis",
    productLabel: "Casino (paquete)",
    directoryGroup: "casino-mx",
  },
  {
    id: "melbet-sportsbook-welcome",
    casinoId: "melbet",
    title: "Bono deportivo: hasta MX$17,500 en 4 depósitos",
    type: "welcome",
    terms:
      "Paquete para los primeros cuatro depósitos elegibles: 100% hasta MX$7,000, 50% hasta MX$3,500, 25% hasta MX$3,500 y 25% hasta MX$3,500. Depósito mínimo MX$100. Requisito de apuesta 5x según términos publicados. Aplican cuotas mínimas, vigencia, verificación, mercados elegibles y restricciones del operador.",
    active: true,
    product: "sportsbook",
    market: "mx",
    status: "active-variable",
    offerLabel: "Hasta MX$17,500 en 4 depósitos",
    minDeposit: "MX$100",
    wagering: "5x (deportivo, según términos)",
    productLabel: "Apuestas",
    directoryGroup: "sports-mixed",
  },
  {
    id: "awintura-welcome",
    casinoId: "awintura",
    title: "Hasta $60,000 + 250 FS + 200% freebets según campaña",
    type: "welcome",
    terms:
      "La moneda, importes, depósitos elegibles, wagering, cuotas, juegos, límites, vencimiento y disponibilidad dependen de la creatividad activa, la cuenta, el GEO y los términos oficiales.",
    active: true,
    product: "mixed",
    market: "latam",
    status: "active-variable",
    offerLabel: "Hasta $60,000 + 250 FS + 200% freebets según campaña",
    productLabel: "Casino + apuestas",
    directoryGroup: "casino-mx",
  },
  {
    id: "mostbet-first-deposit",
    casinoId: "mostbet",
    title: "125% + 250 FS en el primer depósito según campaña",
    type: "welcome",
    terms:
      "La landing suministrada permite seleccionar Casino o Sports. El importe máximo, moneda, depósito mínimo, wagering, free spins, juegos, mercados, cuotas, vencimiento, KYC y disponibilidad dependen de la campaña, cuenta, GEO y términos vigentes.",
    active: true,
    product: "mixed",
    market: "latam",
    status: "active-variable",
    offerLabel: "125% + 250 FS en el primer depósito según campaña",
    productLabel: "Casino o Sports",
    directoryGroup: "sports-mixed",
  },
  {
    id: "sportsbetio-champions-welcome",
    casinoId: "sportsbetio",
    title: "100% hasta 300 USDT para Sports o Casino",
    type: "welcome",
    terms:
      "Depósito mínimo de 10 USDT. Wagering publicado: 15x para Sports y 40x para Casino. Activación, mercados, juegos, vencimiento, KYC, pagos y disponibilidad dependen de la cuenta, GEO y términos vigentes.",
    active: true,
    product: "mixed",
    market: "global",
    status: "active-variable",
    offerLabel: "100% hasta 300 USDT (Sports o Casino)",
    minDeposit: "10 USDT",
    wagering: "15x Sports / 40x Casino",
    productLabel: "Sports o Casino",
    directoryGroup: "sports-mixed",
  },
  {
    id: "bitcasino-three-deposit-welcome",
    casinoId: "bitcasino",
    title: "Hasta 5,000 USDT en tres bonos de depósito",
    type: "welcome",
    terms:
      "Primer depósito: 100% hasta 1,500 USDT. Segundo depósito: 50% hasta 2,000 USDT. Tercer depósito: 100% hasta 1,500 USDT. Activación, moneda, depósito mínimo, wagering, juegos elegibles, vencimiento, KYC y disponibilidad dependen de la cuenta, GEO y términos vigentes.",
    active: true,
    product: "casino",
    market: "global",
    status: "active-variable",
    offerLabel: "Hasta 5,000 USDT en tres depósitos",
    productLabel: "Casino crypto",
    directoryGroup: "crypto-rewards",
    featuredPosition: 3,
  },
  {
    id: "mellstroy-welcome",
    casinoId: "mellstroy",
    title: "Bono de bienvenida: hasta 660% + 400 FS",
    type: "welcome",
    terms:
      "La página de promociones suministrada muestra hasta 660% + 400 FS, mientras que otra creatividad de registro muestra 550% + 400 FS. La oferta puede variar según campaña, registro, cuenta, elegibilidad, jurisdicción y términos vigentes. Confirma porcentajes, depósitos elegibles, wagering, juegos, límites y vencimiento antes de depositar.",
    active: true,
    product: "casino",
    market: "global",
    status: "active-variable",
    offerLabel: "Hasta 660% + 400 FS según campaña",
    productLabel: "Casino crypto",
    directoryGroup: "crypto-rewards",
  },
  {
    id: "vodkabet-welcome",
    casinoId: "vodkabet",
    title: "125% en el primer depósito + hasta 300 FS según campaña",
    type: "welcome",
    terms:
      "Código JUGADAMAX. Las creatividades también muestran +2% para depósitos crypto y 50 FS por vincular Telegram. Depósito mínimo, wagering, juegos elegibles, vencimiento, límites y disponibilidad deben confirmarse en los términos oficiales.",
    active: true,
    product: "casino",
    market: "global",
    status: "active-variable",
    offerLabel: "125% + hasta 300 FS según campaña",
    productLabel: "Casino crypto",
    directoryGroup: "crypto-rewards",
  },
  {
    id: "gamdom-rewards-welcome",
    casinoId: "gamdom",
    title: "Rakeback elevado al 15% durante 7 días según campaña Rewards",
    type: "cashback",
    terms:
      "Promoción Rewards publicada por Gamdom. El rakeback elevado, la duración, elegibilidad, juegos, límites y disponibilidad dependen de la campaña, cuenta, GEO y términos oficiales. No es un bono de bienvenida estándar con depósito match fijo.",
    active: true,
    product: "rewards",
    market: "global",
    status: "active-variable",
    offerLabel: "Rakeback 15% durante 7 días según campaña",
    productLabel: "Rewards / rakeback",
    directoryGroup: "crypto-rewards",
  },
];
